### ISSUE TITLE
VLC doesn't detect/find libmmbd/aacs

### ISSUE THREAD

**Issue by Extarys** [flathub/org.videolan.VLC.Plugin.makemkv#2]
I installed flatpak MakeMKV and this flatpak, registered with the beta key, even rebooted the computer.
VLC is unable to decrypt the bluray and no instruction seems to be provided here or on the makemkv forum.

I tried with VLC native and flatpak.

Does anyone have an idea how is this suppose to work? Been trying and searching for 2 hours :cry:

**Comment by MatMaul** [comment]
can you try updating to last version, and install branch `3-21.08` of makemkv VLC plugin ?

I just test it again in this conf and it works for me.

If not, perhaps the bdj plugin could help too, and if not again, could you provides info logs, by doing `flatpak run org.videolan.VLC -vv` and opening your bluray with the VLC menu ?

**Comment by HeaDBanGer84** [comment]
for me installing the makemkv polugin fixed it:
```
flatpak install flathub org.videolan.VLC.Plugin.makemkv
```
picked the current version and done.
